version: "3.3"

services:

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "2080:80"
      - "28080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  web1:
    image: "traefik/whoami"
    #container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web1.rule=Host(`web1`)"
      - "traefik.http.routers.web1.entrypoints=web"
    deploy:
        replicas: 2

  web2:
    image: "traefik/whoami"
    #container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web2.rule=Host(`web2`)"
      - "traefik.http.routers.web2.entrypoints=web"
    deploy:
        replicas: 2

