version: "3.3"

services:

  traefik:
    image: "traefik:v2.6"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "2080:80"
      - "28080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  web1:
    image: "traefik/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web1.rule=PathPrefix(`/apps/web1`) || Host(`web1`)"
      - "traefik.http.routers.web1.entrypoints=web"

      - "traefik.http.routers.web1.middlewares=web1@docker"
      - "traefik.http.middlewares.web1.ratelimit.average=2"
      - "traefik.http.middlewares.web1.ratelimit.period=1m"
      - "traefik.http.middlewares.web1.ratelimit.burst=20"
      #- "traefik.http.middlewares.web1.plugin.inflightreq.amount=10"
    deploy:
        replicas: 2

  web2:
    image: "traefik/whoami"
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.web2.rule=Host(`web2`) || Path(`/apps/web2`)"
      - "traefik.http.routers.web2.rule=PathPrefix(`/apps/web2`) || Host(`web2`)"
      - "traefik.http.routers.web2.entrypoints=web"
    deploy:
        replicas: 2

