version: "3.3"

services:

  traefik:
    image: "traefik:v2.6"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "2080:80"
      - "28080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  web1:
    image: "traefik/whoami"

    deploy:
      mode: replicated
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.http.routers.web1.rule=PathPrefix(`/apps/web1`) || Host(`web1`)"
        - "traefik.http.routers.web1.entrypoints=web"
        - "traefik.http.services.web1.loadbalancer.server.port=80"
        - "traefik.http.routers.web1.middlewares=web1-limit@docker,web1-prefix@docker"

        - "traefik.http.middlewares.web1-prefix.stripprefix.prefixes=/apps/web1,/fiibar"


        - "traefik.http.middlewares.web1-limit.ratelimit.average=2"
        - "traefik.http.middlewares.web1-limit.ratelimit.period=1m"
        - "traefik.http.middlewares.web1-limit.ratelimit.burst=20"
        #- "traefik.http.middlewares.web1-plugin.plugin.inflightreq.amount=10"


